#!/bin/bash
while IFS=":" read -r username _ _ _ _ home_directory _; do
    echo "User: $username"
    echo "Home Directory: $home_directory"
    echo "----------------------"
done < /etc/passwd | sort -k2

